name: CI of mc_pepper

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    # Run on Sunday, Tuesday and Thursday nights
    - cron: '0 23 * * 0,1,4'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install mc_rtc
      run: |
        set -x
        set -e
        curl -1sLf 'https://dl.cloudsmith.io/public/mc-rtc/head/setup.deb.sh' | sudo -E bash
        sudo apt-get install -qq libmc-rtc-dev
    - name: Install pepper_description
      run: |
        set -x
        set -e
        if [ "${{ matrix.os }}" = "ubuntu-18.04" ]
        then
          export ROS_DISTRO="melodic"
        else
          export ROS_DISTRO="noetic"
        fi
        sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
        wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        sudo apt-get update -qq
        sudo apt-get -qq remove libomp5-9 || true
        sudo apt-get install -qq ros-${ROS_DISTRO}-libfranka ros-${ROS_DISTRO}-franka-ros
        . /opt/ros/${ROS_DISTRO}/setup.bash
        mkdir -p /tmp/catkin_ws/src
        cd /tmp/catkin_ws/src
        catkin_init_workspace
        git clone --recursive https://github.com/jrl-umi3218/pepper_description
        cd ../
        catkin_make
        . devel/setup.bash
        echo "ROS_DISTRO=${ROS_DISTRO}" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}" >> $GITHUB_ENV
        echo "ROS_MASTER_URI=${ROS_MASTER_URI}" >> $GITHUB_ENV
        echo "ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}" >> $GITHUB_ENV
        echo "PYTHONPATH=${PYTHONPATH}" >> $GITHUB_ENV
        echo "CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}" >> $GITHUB_ENV
        echo "PATH=${PATH}" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" >> $GITHUB_ENV
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: gcc
        build-type: RelWithDebInfo
